export 'package:flutter/material.dart';
export 'package:get/get_navigation/src/root/get_material_app.dart';
export 'package:web_info/pages/HomePage.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:web_info/config/icons.dart';
export 'package:web_info/components/Home/Titlebar.dart';
export 'package:web_info/config/images.dart';
export 'package:google_fonts/google_fonts.dart';
export 'package:web_info/config/colors.dart';
